MACHINES = {
:kali => {
#        :box_name => "lejer/kali",
        :box_name => "kalilinux/rolling",
        :net => [
                   {ip: '192.168.10.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "net"},
                ]
  },

:centos => {
      :box_name => "centos/7",
      :net => [
                 {ip: '192.168.10.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "net"},
                
               ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        case boxname.to_s
        when "kali"
          config.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
          end

        when "centos"
          config.vm.provider "virtualbox" do |v|
            v.memory = 2024
            v.cpus = 2
          end
        end

      end

  end  
end

